"""Generate/check canonical non-benchmark leaderboard prompt snapshots."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from fwcollab.c5 import project_role_observation  # noqa: E402
from fwcollab.symbolic.agents import (  # noqa: E402
    AgentDecision, CoordinationMessage, build_agent_prompt,
)
from fwcollab.symbolic.rules import public_rulebook  # noqa: E402

OUT = ROOT / "eval_private/leaderboard_v1/prompt_contract"
TRACKS = ("core", "information", "sync", "join")
ROLES = ("F", "W")
SOURCE_HASHES = {
    "src/fwcollab/symbolic/agents.py": "a6d06b75e3c8dc9ee16b4fa9f8c431c37412170a05143abbb9740623e9fdd4f3",
    "src/fwcollab/symbolic/rules.py": "350e5b68ac8b88da11aabd577f7a68168f524debcd8dea0ca2f68fa0fe46da4e",
    "src/fwcollab/c5.py": "a3b1d5bc7b51cef3ab22bbda349123378061b435c9aeb103a1adbd07253e7629",
    "src/fwcollab/symbolic/runner.py": "6556a92d7e570b249091d979591a71dda15b84da767ec208ce0c8380e240b100",
}


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _json_bytes(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _base_observation(track: str) -> dict[str, Any]:
    width = 21
    rows = ["#" * width for _ in range(17)]
    rows[1] = "#F.1A.............f#"
    rows[3] = "#...................#"
    rows[12] = "#W........B........w#"
    return {
        "format": "fwcollab.agent_observation.v1",
        "map_id": f"SYNTHETIC-PROMPT-CONTRACT-{track.upper()}",
        "coordination_mode": "emergent",
        "clock": {"round": 3, "max_rounds": 80 if track != "information" else 30, "rounds_used": 2, "rounds_remaining": 78 if track != "information" else 28},
        "map": {"height": 17, "width": width, "current_rows": rows, "terrain_rows": rows},
        "mechanisms": {
            "exits": {"F": [1, 19], "W": [12, 19]},
            "controllers": {"toy_controller": {"kind": "plate", "position": [1, 3], "accepts": ["F"]}},
            "actuators": {"toy_gate": {"kind": "door", "positions": [[1, 4]], "controlled_by": {"mode": "all", "inputs": ["toy_controller"]}}},
        },
        "dynamic_state": {
            "actors": {"F": [1, 1], "W": [12, 1]}, "alive": {"F": True, "W": True},
            "crates": [], "orbs": [], "controllers": {"toy_controller": False},
            "actuators": {"doors": {"toy_gate": False}},
        },
        "last_transition": {"round": 2, "public_events": [], "feedback": {"F": "waited", "W": "waited"}},
        "shared_message_history": [{"sender": "W", "recipient": "F", "sent_round": 1, "delivery_round": 2, "text": "synthetic ready"}],
        "rules": public_rulebook(),
        "status": "running",
    }


def _observation(track: str, role: str) -> dict[str, Any]:
    base = _base_observation(track)
    if track != "information":
        return base
    task = {
        "wiring": {"toy_controller": "toy_gate"},
        "required_actuator": "toy_gate",
        "f_exit": [1, 19], "w_exit": [12, 19],
    }
    return project_role_observation(base, task, role)


def _inbox(role: str) -> list[dict[str, Any]]:
    teammate = "W" if role == "F" else "F"
    return [{
        "sender": teammate, "recipient": role, "sent_round": 1, "delivery_round": 2,
        "based_on_state_hash": "synthetic-state-hash", "text": "synthetic ready",
        "payload": {"stage": "toy_gate", "status": "READY", "fact": "toy condition checked", "request": "continue synthetic example", "until": "toy condition complete"},
    }]


def _history(role: str) -> list[dict[str, Any]]:
    # Nine items intentionally exercise the prompt builder's last-eight rule.
    return [{
        "round": index, "observation_hash": f"synthetic-{index}",
        "action": {"move": "WAIT", "steps": 0}, "subgoal": "synthetic contract",
        "commitment": f"{role} synthetic commitment", "expected_teammate": "synthetic response",
        "message": None, "feedback": "waited", "resulting_status": "running",
    } for index in range(1, 10)]


def _schema_contract() -> dict[str, Any]:
    return {
        "format": "fwcollab.leaderboard.observation_contract.v1",
        "fixture": "fixed synthetic non-benchmark observation generated by scripts/freeze_leaderboard_prompt_contract.py",
        "common_format": "fwcollab.agent_observation.v1",
        "information_format": "fwcollab.c5_agent_observation.v1",
        "common_top_level_fields": ["format", "map_id", "coordination_mode", "clock", "map", "mechanisms", "dynamic_state", "last_transition", "shared_message_history", "rules", "status"],
        "information_additional_fields": ["information_condition", "private_information"],
        "role_history": {"independent": True, "maximum_items_rendered": 8, "selection": "own_history[-8:]"},
        "inbox": {"public_structured_messages_only": True, "delay_rounds": 1},
        "system_message": {"present": False, "wire_contract": "Responses input=user prompt string; Chat Completions one user message only"},
    }


def expected_files() -> dict[str, bytes]:
    files: dict[str, bytes] = {
        "action_schema.json": _json_bytes(AgentDecision.model_json_schema()),
        "message_schema.json": _json_bytes(CoordinationMessage.model_json_schema()),
        "observation_contract.json": _json_bytes(_schema_contract()),
    }
    for track in TRACKS:
        for role in ROLES:
            files[f"{track}_{role}_system.txt"] = b""
            prompt = build_agent_prompt(role, _observation(track, role), _inbox(role), _history(role), communication_enabled=True)
            files[f"{track}_{role}_user.txt"] = prompt.encode("utf-8")
    return files


def _manifest(files: dict[str, bytes]) -> dict[str, Any]:
    entries = []
    for name, data in sorted(files.items()):
        parts = name.rsplit("_", 2)
        track = parts[0] if name.endswith(("_system.txt", "_user.txt")) else None
        role = parts[1] if track else None
        entries.append({
            "file": name, "sha256": _sha(data), "bytes": len(data),
            "track": track, "role": role,
            "prompt_builder": "fwcollab.symbolic.agents.build_agent_prompt" if track else None,
            "prompt_builder_source_sha256": SOURCE_HASHES["src/fwcollab/symbolic/agents.py"] if track else None,
        })
    return {
        "format": "fwcollab.leaderboard.prompt_contract.v1",
        "status": "frozen_reproducibility_snapshot", "benchmark_content_used": False, "model_api_calls": 0,
        "system_prompt": "No system message is sent; system snapshot files are exactly zero bytes.",
        "fixture": "fixed synthetic non-benchmark observation/inbox/history",
        "source_hashes": SOURCE_HASHES, "files": entries,
    }


def _verify_sources() -> None:
    for relative, expected in SOURCE_HASHES.items():
        actual = _sha((ROOT / relative).read_bytes())
        if actual != expected:
            raise RuntimeError(f"prompt source changed: {relative}: {actual} != {expected}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    _verify_sources()
    files = expected_files()
    manifest = _json_bytes(_manifest(files))
    if args.check:
        for name, expected in {**files, "prompt_contract_manifest.json": manifest}.items():
            path = OUT / name
            if not path.is_file() or path.read_bytes() != expected:
                raise RuntimeError(f"prompt snapshot mismatch: {name}")
        print("PASS prompt snapshots exactly reproduce; model/API calls=0")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (OUT / name).write_bytes(data)
    (OUT / "prompt_contract_manifest.json").write_bytes(manifest)
    print(f"wrote {len(files) + 1} files; model/API calls=0")


if __name__ == "__main__":
    main()
